version: '3.8'

services:
  backend:
    # Si vous n'avez pas encore envoyé l'image en ligne, gardez "build: ./backend"
    # Mais il faut impérativement utiliser l'option "Repository" (Git) dans Portainer.
    build: ./backend
    container_name: downloadix-backend
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - /mnt/data/downloads:/app/downloads
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    container_name: downloadix-frontend
    restart: unless-stopped
    ports:
      - "2034:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
