version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: downloadix-backend
    restart: unless-stopped
    # Le backend reste sur son port interne 5000, 
    # il n'a pas besoin d'être exposé vers l'extérieur.
    expose:
      - "5000"
    volumes:
      - /mnt/votre_pool/downloads:/app/downloads
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
    container_name: downloadix-frontend
    restart: unless-stopped
    ports:
      - "2034:80" # L'application sera accessible sur http://IP_TRUENAS:2034
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
