version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: downloadix-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # REMPLACEZ '/mnt/votre_pool/downloads' par votre vrai chemin TrueNAS
      - /mnt/votre_pool/downloads:/app/downloads
      - backend_settings:/app
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./frontend
    container_name: downloadix-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://IP_DE_VOTRE_TRUENAS:5000

volumes:
  backend_settings:
